name: Demo CI

on:
  push:
    branches: [main]

jobs:
  mongo-init:
    runs-on: ubuntu-latest

    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      PORT: ${{ secrets.PORT }}

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Wait for MongoDB to be ready
        run: |
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB..."
            sleep 1
          done
          echo "MongoDB is up and running!"

      - name: Seed database
        working-directory: ./backend
        run: |
          npm install
          node seed.js

      - name: Run backend tests
        working-directory: ./backend
        run: |
          npm test

  test:
    runs-on: ubuntu-latest
    needs: mongo-init

    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      PORT: ${{ secrets.PORT }}

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Wait for MongoDB to be ready
        run: |
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB..."
            sleep 1
          done
          echo "MongoDB is up and running!"

      - name: Install dependencies and run tests
        working-directory: ./backend
        run: |
          npm install
          npm test
